### ISSUE TITLE
Add config pack example

### ISSUE THREAD

**Issue by pgreze** [pgreze/circleci-howto#1]
# CircleCI configuration

This setup is relying on:

- dynamic config using setup workflows: see [this discuss](https://discuss.circleci.com/t/intro-to-dynamic-config-via-setup-workflows/39868) or [this blog post](https://circleci.com/blog/building-cicd-pipelines-using-dynamic-config/) for explanations.
- [circleci config pack](https://circleci.com/docs/how-to-use-the-circleci-local-cli/#packing-a-config) which implements [FYAML](https://github.com/CircleCI-Public/fyaml), a scheme for breaking YAML documents across files in a directory tree.

# main file

```
version: 2.1
setup: true

orbs:
  circleci-cli: circleci/circleci-cli@0.1.9
  continuation: circleci/continuation@0.3.0

jobs:
  config_gen:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - circleci-cli/install
      - run:
          name: "Generate YAML config from circleci/"
          command: circleci config pack circleci/ > .circleci/config_gen.yml
      - continuation/continue:
          configuration_path: .circleci/config_gen.yml

workflows:
  setup:
    jobs:
        - config_gen
```

in circleci/@root.yml:

```
version: 2.1

parameters:
  custom-param:
    type: integer
    default: 4

orbs:
  # https://circleci.com/developer/orbs/orb/circleci/slack
  # Notice: requires SLACK_ACCESS_TOKEN to be set in the project settings.
  slack: circleci/slack@4.2.0
```

etc...
